project_id = "zcjasjicjrvqtxtqvdwr"

[functions.build-story]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-all-images]
verify_jwt = false

[functions.search-image-library]
verify_jwt = false

[functions.add-to-library]
verify_jwt = false

[functions.backfill-image-library]
verify_jwt = false

[functions.backfill-approval-check]
verify_jwt = false

[functions.upgrade-to-high-res]
verify_jwt = false

[functions.add-interactive-elements]
verify_jwt = false

[functions.kids-create]
verify_jwt = false

[functions.kids-delete]
verify_jwt = false

[functions.kids-extract-descriptor]
verify_jwt = false

[functions.kids-get]
verify_jwt = false

[functions.kids-list]
verify_jwt = false

[functions.kids-update]
verify_jwt = false

[functions.kids-upload-photo]
verify_jwt = false

[functions.stories-list]
verify_jwt = false

[functions.prepare-kid-refs]
verify_jwt = false

[functions.mark-page-as-reference]
verify_jwt = false

[functions.unmark-page-reference]
verify_jwt = false

[functions.get-kid-references]
verify_jwt = false

[functions.stories-get]
verify_jwt = false

[functions.export-pdf]
verify_jwt = false